[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["lib/openzeppelin-contracts/contract=@openzeppelin/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
